// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// TableCheck TableCheck configures a single latency check for a table
// swagger:model TableCheck
type TableCheck struct {

	// latency spec
	LatencySpec *LatencySpec `json:"latencySpec,omitempty"`

	// table name
	TableName string `json:"tableName,omitempty"`

	// SchemaOwner associates an owner for a given schema. It can be overridden at the table level. It defaults to eng-deip
	TableOwner string `json:"tableOwner,omitempty"`
}

// Validate validates this table check
func (m *TableCheck) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLatencySpec(formats); err != nil {
		// prop
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TableCheck) validateLatencySpec(formats strfmt.Registry) error {

	if swag.IsZero(m.LatencySpec) { // not required
		return nil
	}

	if m.LatencySpec != nil {

		if err := m.LatencySpec.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("latencySpec")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *TableCheck) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TableCheck) UnmarshalBinary(b []byte) error {
	var res TableCheck
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
