// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// Thresholds Thresholds holds values for all of the different thresholds we might want to check against. Null values are not overridden, empty values are "unset", to not alert at that level. Otherwise, each `threshold` expects a string formatted Golang duration
// swagger:model Thresholds
type Thresholds struct {

	// critical
	Critical string `json:"critical,omitempty"`

	// major
	Major string `json:"major,omitempty"`

	// minor
	Minor string `json:"minor,omitempty"`
}

// Validate validates this thresholds
func (m *Thresholds) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *Thresholds) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Thresholds) UnmarshalBinary(b []byte) error {
	var res Thresholds
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
