required = ["github.com/jteeuwen/go-bindata/go-bindata", "github.com/golang/mock/mockgen"]

[[constraint]]
  name = "github.com/Clever/pq"

[[constraint]]
  name = "github.com/hashicorp/go-multierror"
  version = "1.0.0"

[[constraint]]
  name = "github.com/kardianos/osext"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "gopkg.in/Clever/kayvee-go.v6"
  version = "6.24.0"

[[constraint]]
  branch = "master"
  name = "github.com/jteeuwen/go-bindata"

[[constraint]]
  branch = "master"
  name = "github.com/golang/mock"
