env:
- TRACING_ACCESS_TOKEN
- TRACING_INGEST_URL
- REDSHIFT_PROD_DATABASE
- REDSHIFT_PROD_USER
- REDSHIFT_PROD_PASSWORD
- REDSHIFT_PROD_HOST
- REDSHIFT_PROD_PORT
- REDSHIFT_FAST_DATABASE
- REDSHIFT_FAST_USER
- REDSHIFT_FAST_PASSWORD
- REDSHIFT_FAST_HOST
- REDSHIFT_FAST_PORT
- RDS_INTERNAL_DATABASE
- RDS_INTERNAL_USER
- RDS_INTERNAL_PASSWORD
- RDS_INTERNAL_HOST
- RDS_INTERNAL_PORT
- RDS_EXTERNAL_DATABASE
- RDS_EXTERNAL_USER
- RDS_EXTERNAL_PASSWORD
- RDS_EXTERNAL_HOST
- RDS_EXTERNAL_PORT
- SNOWFLAKE_DATABASE
- SNOWFLAKE_USER
- SNOWFLAKE_PASSWORD
- SNOWFLAKE_ACCOUNT
- SNOWFLAKE_WAREHOUSE
- SNOWFLAKE_ROLE
- LATENCY_CONFIG
resources:
  cpu: 0.25
  max_mem: 0.5
shepherds:
- benji.stein@clever.com
expose:
- name: default
  port: 80
  health_check:
    type: http
    path: /_health
team: eng-deip
autoscaling:
  metric: cpu
  metric_target: 50
  min_count: 2
# for the full spec on alarms, see catapult's swagger.yml definition for Alarm
#    link: https://github.com/Clever/catapult/blob/master/swagger.yml
#    best practices: https://clever.atlassian.net/wiki/spaces/~620990898/pages/904036784/Alarm+Best+Practices
alarms:
- type: InternalErrorAlarm
  severity: critical
  parameters:
    threshold: 0.05
  extraParameters:
    source: Total
    errorMinimum: 20
- type: InternalErrorAlarm
  severity: major
  parameters:
    threshold: 0.01
  extraParameters:
    source: Total
- type: InternalErrorAlarm
  severity: major
  parameters:
    threshold: 0.002
    evaluationPeriods: 5
  extraParameters:
    source: Total
- type: InternalErrorAlarm
  severity: minor
  parameters:
    threshold: 0.001
  extraParameters:
    source: Total
- type: BadRequestAlarm
  severity: major
  parameters:
    threshold: 0.15
  extraParameters:
    errorMinimum: 20
- type: BadRequestAlarm
  severity: minor
  parameters:
    threshold: 0.05
pod_config:
  dev:
    migrationState: deployable
  group: us-west-1
  prod:
    migrationState: deployable
